services:

  hack-backend:
    image: backend
    build:
      context: ./backend
      target: builder
    container_name: backend-new
    env_file:
      - .env
    environment:
      PORT: 80
      MAX_WORKERS: 1
    ports:
      - '8082:80'
      - '5684:5684'
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]